### ISSUE TITLE
Footer glide or fade in on hover

### ISSUE THREAD

**Issue by ostheperson** [OS-the-Person/OS_google_clone#1]
I’m willing to hold your hand so you can make your first PR. This issue is a bit easier than normal. And anyone who’s already contributed to open source isn’t allowed to touch this one!

I am trying to make "google search page on steroids" 

If you know any cool CSS/JavaScript frontend features to add to this cloned google page please, go all out and do it.

N//B to keep it beginner-friendly use vanilla JS.
Issue:
-Footer gliding upwards when pointer/focus hovers the lower part of the screen.

**Comment by pavkrol** [comment]
Hey. I would like to work on this issue if it’s still available.

**Comment by ostheperson** [comment]
pavkrol, sorry for the late reply it is still open
Your task is to cause the footer of the search page to not be visible on load 
THEN 
slide up (preferably quite quick, like less than 1/4 of a second) on pointer hover. 
THEN
slide back down when the pointer is away
N//B
- don't allow the footer to be completely invisible (let the user know there is something there).
I will allow you to add your creative thoughts and not tell you what exactly to do. GOOD LUCK
