### ISSUE TITLE
Search Bar Maximization

### ISSUE THREAD

**Issue by ostheperson** [OS-the-Person/OS_google_clone#2]
Make the
-search bar a circle at the center of its position.
-When pointer hover's around the area it should maximize to the full size.

**Comment by Shivaansh-Agarwal** [comment]
Can you please clarify this issue like what do you want to achieve?

**Comment by Shivaansh-Agarwal** [comment]
And I would like to work on this issue.

**Comment by ostheperson** [comment]
Great :)

Firstly, the search bar should have a small width so that the rounded edges would make the search box appear like a circle and on mouse hover it should expand to the default width for typing

**Comment by conorcode** [comment]
Is it possible for two persons to work on the same issue or not? If it is I would also like to contribute. Thank you.

**Comment by Shivaansh-Agarwal** [comment]
> Great :)
> 
> Firstly, the search bar should have a small width so that the rounded edges would make the search box appear like a circle and on mouse hover it should expand to the default width for typing

I've raised the PR for the same.

**Comment by DevDownUnder** [comment]
I'll jump in line on this one please. Cheers
